version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
    networks:
      - monitorapramim-net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - monitorapramim-net

  backend:
    build: ./backend
    container_name: backend
    networks:
      - monitorapramim-net
    depends_on:
      - db
      - amazon-service
      - whatsapp-service

  amazon-service:
    build: ./amazon-service
    container_name: amazon-service
    networks:
      - monitorapramim-net

  whatsapp-service:
    build: ./whatsapp-service
    container_name: whatsapp-service
    networks:
      - monitorapramim-net

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: monitorapramim
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - monitorapramim-net

networks:
  monitorapramim-net:

volumes:
  dbdata:
